name: 'Run Konflux UI E2E tests'
description: 'Executes E2E tests for Konflux UI using Cypress'
runs:
  using: composite
  steps:
  - name: Run Konflux UI E2E tests
    env:
      CYPRESS_GH_TOKEN: ${{ env.HAC_TEST_GH_TOKEN }}
      TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
      PR_NUMBER: ${{ env.PR_NUMBER }}
      HEAD_SHA: ${{ env.HEAD_SHA }}
      CYPRESS_USERNAME: ${{ env.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ env.CYPRESS_PASSWORD }}
      SEALIGHTS_TOKEN: ${{ env.SEALIGHTS_TOKEN }}
    shell: bash
    run: |
      : Run Konflux UI E2E tests
      ./pr_check.sh test