---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dummy-pipeline
  namespace: kkanova-tenant
spec:
  tasks:
    - name: dummy-task
      steps:
        - name: dummy-step
          image: alpine
          script: |
            echo "Hello, world!"
